version: '3.8'
services:
  # Service Airflow Webserver
  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow_server
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: standalone # Chế độ chạy tất cả trong 1 container cho gọn